### ISSUE TITLE
Post Grid Block Pixelated Images

### ISSUE THREAD

**Issue by jacquesvdhorst** [lightspeeddevelopment/lsx-blocks#11]
We've been noticing that the post grid block has been adding the **sizes="(max-width: 400px) 50vw, 10vw"** attribute and this is causing the images to get pixelated. If that is removed the images display fine. I've had a look in the code but can't see how its being added.

You can see this currently here: https://menswear.feedmybeta.com/

![Screenshot 2019-08-07 at 12 37 14](https://user-images.githubusercontent.com/35291167/62616542-1980d680-b910-11e9-85fe-e5c1311e13a8.png)

**Comment by viscosho** [comment]
@jacquesvdhorst  closing this one, just tested the issue and this has been fixed on this commit: https://github.com/lightspeeddevelopment/lsx-blocks/commit/778c7127de3155b3b92c17f79bdd9144c67a6859
