### ISSUE TITLE
The Page Title from the block editor settings is not showing on frontend

### ISSUE THREAD

**Issue by joseabreu1985** [lightspeeddevelopment/lsx-blocks#112]
### Describe the bug
The page title option from the block editor settings is not showing on frontend

### Steps to Reproduce
1. Go to a page with the block editor
2. Click on page editor right sidebar page title option and enable it
3. Set any configuration you want (Alignment, width, color, etc)
4. Go to the front of the page you are applying this option and see the title is not showing as expected 

### Expected behavior
The page title should show in the frontend with any options you picked from the editor.

### Screenshots

<img width="1279" alt="title-banner-block-editor-settings" src="https://user-images.githubusercontent.com/20842182/91590170-ecdb9a80-e928-11ea-8a96-019503bbff1b.png">

### Environment information
 - Device: All of them
 - OS: All of them
 - Browser and version: All of them
 - WordPress version: 5.5

**Comment by viscosho** [comment]
This functionality is deprecated
