### ISSUE TITLE
Remove hard-coded links to CTT dev site.

### ISSUE THREAD

**Issue by eleshar** [lightspeeddevelopment/lsx-blocks#4]
https://github.com/lightspeeddevelopment/lsx-blocks/blob/44257c42a2462a74b8275b6ae64a830ff6e7e1d6/bin/cardheight.js#L16-L17

**Comment by eleshar** [comment]
https://github.com/lightspeeddevelopment/lsx-blocks/blob/44257c42a2462a74b8275b6ae64a830ff6e7e1d6/bin/compare-1.php#L1

**Comment by eleshar** [comment]
https://github.com/lightspeeddevelopment/lsx-blocks/blob/44257c42a2462a74b8275b6ae64a830ff6e7e1d6/bin/compare-2.php#L1

**Comment by krugazul** [comment]
The Bin folder has been removed, making this null and void
