### ISSUE TITLE
meta_key: lsx_disable_title postmeta should be restricted to content that needs it

### ISSUE THREAD

**Issue by eleshar** [lightspeeddevelopment/lsx-blocks#44]
### Describe the bug
meta_key: lsx_disable_title postmeta is not limited to content only where needed, for example, WooCommerce Action Scheduler prior to version 3.0 (current version used on most sites) utilizes a custom post type for their 'actions', all these actions are being written with the meta_key: lsx_disable_title resulting in numerous useless postmeta data caused by LSX Blocks.

### Screenshots
See export - https://docs.google.com/spreadsheets/d/1SZgKjMKMjibh9LElWNSnp773z_db12GoBvbOWspQQkA/edit?usp=sharing

**Comment by viscosho** [comment]
The function that calls this metabox has been limited to only posts on this commit: https://github.com/lightspeeddevelopment/lsx-blocks/commit/29b9ffd4174fa61eecebeecaf75f72370d81de11
