### ISSUE TITLE
LSX Blocks is using the development build of React

### ISSUE THREAD

**Issue by eleshar** [lightspeeddevelopment/lsx-blocks#45]
### Describe the bug
LSX Blocks is using the development build of React. 

### Steps to Reproduce

1. Setup new WordPress install
2. Activate LSX Blocks plugin
3. Install React Developer Tools Chrome extension
4. Open page/post in the block editor.

### Expected behaviour
Use the Production Build of React

If you’re benchmarking or experiencing performance problems in your React apps, make sure you’re testing with the **minified production build.**

By default, React includes many helpful warnings. These warnings are very useful in development. However, they make React larger and slower so you should make sure to use the production version when you deploy the app.

Ref - https://reactjs.org/docs/optimizing-performance.html#use-the-production-build

### Screenshots
![image](https://user-images.githubusercontent.com/1577675/76017657-9ec07e00-5f27-11ea-8097-875e0b689451.png)

**Comment by viscosho** [comment]
All files related to React are compiled for production now, this happened on this PR: https://github.com/lightspeeddevelopment/lsx-blocks/pull/48

Note: The wp-config.php file must NOT have the "SCRIPT_DEBUG" defined as true.
