### ISSUE TITLE
Variables should be declared explicitly

### ISSUE THREAD

**Issue by eleshar** [lightspeeddevelopment/lsx-blocks#5]
Add the "let", "const" or "var" keyword to this declaration of "slick" to make it explicit.

`let `and `const ` was introduced in ECMAScript 2015, and are now the preferred keywords for variable declaration.

https://github.com/lightspeeddevelopment/lsx-blocks/blob/44257c42a2462a74b8275b6ae64a830ff6e7e1d6/bin/cardheight.js#L1

**Comment by krugazul** [comment]
The Bin folder has been removed,  we will take note of using explicit declarations in future
