### ISSUE TITLE
Adding subheadings is time-consuming

### ISSUE THREAD

**Issue by ashleyshaw** [lightspeeddevelopment/lsx-blocks#61]
### CHALLENGE: Adding subheadings is time-consuming
- When doing block editor content management, adding subheadings can be time-consuming. 
- We have used subtitles for many years and we always use a standard approach for styling them, this became evident when creating Heading and Subheading sections.
- The space surrounding heading and subheading needs to balance with other elements.
- We need to decide how the LightSpeed team should handle subheadings going forward, specifically around styling and HTML tags. 

### CURRENT SOLUTION: Manually format a paragraph block for each subheading
- When adding a new heading + subheading, Do not put "lsx-title" class on the H2 or H3 title. 
- Next step is to add a Paragraph block for the subheading and apply the "lsx-title" class to the paragraph text below the title. 
- Set the paragraph text to Large font size, which is font size 36 
- The "lsx-title" class fixes the formatting of the subhead text, without the class the line height is insufficient and text overlaps with it breaks to a second line.

### PROPOSED SOLUTION: Add a Subheading Block Style for Paragraph Block

**Requirements:**
- Define a method for setting subhead size consistently within the block editor. 
- Distinguish subheads from the heading and body copy. 
- Headings and Subheadings need breathing room, make sure we define clear padding rules between the two blocks. 

**Styling Considerations:**
 - Typeface 
 - Size 
 - Weight
 - Style 
 - Colour 

**Solution:**
- The Subheading block that used to be in core used the HTML <p> tag.
- We could create a subheading block style for the paragraph block and this will solve the issue. 

### Additional Considerations:
- HTML Heading tags (H1, H2, etc) denote content hierarchy to search engines.
- h1–h6 elements must not be used to markup subheadings, subtitles, alternative titles and taglines unless intended to be the heading for a new section or subsection.
- Using the right tag to markup the subhead is important, because otherwise search engine may not properly categorise the page.

**Comment by viscosho** [comment]
This was dismissed in favor of a simpler solution, a class that can be added to a group of heading and title, here are the details: https://github.com/lightspeeddevelopment/lsx/issues/385
